name: Run Python in Docker

on:
  push:
    branches:
      - main

jobs:
  run-python-container:
    runs-on: ubuntu-latest

    steps:
      # 1. Configura el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Ejecuta un contenedor de Python
      - name: Run Python container
        uses: addnab/docker-run-action@v3
        with:
          image: python:3.10
          options: --rm
          run: |
            python --version
            echo "Contenedor de python"
            python -c "print('Hola Dorx :), Ojala y gane el Real!, no me repruebes')"